### ISSUE TITLE
HTML structure

### ISSUE THREAD

**Issue by gmagnenat** [gmagnenat/equalizer-landing-page#13]

**Comment by gmagnenat** [comment]
@KingLyrics feel free to start on that part if you want.

**Comment by KingLyrics** [comment]
@gmagnenat alright. So does that mean i can now start making changes to the html document?

**Comment by gmagnenat** [comment]
Sure, by keeping the same process. Add me as reviewer on a pull request when you want to push your update to GitHub and we will explore some other parts of code review. I won't have much time on the week-end but I'm here sometimes.

**Comment by KingLyrics** [comment]
Alright not a problem!

**Comment by KingLyrics** [comment]
@gmagnenat I actually need a copy of the design folder.

**Comment by KingLyrics** [comment]
@gmagnenat Sorry about that. I have just seen it on figma.

**Comment by KingLyrics** [comment]
@gmagnenat  Drafted html structure has been put up.

**Comment by gmagnenat** [comment]
Nice! I'll have a look over the weekend and add my comments. With a quick check it looks like we can simplify some parts.
