### ISSUE TITLE
Useful git commands

### ISSUE THREAD

**Issue by gmagnenat** [gmagnenat/equalizer-landing-page#35]

**Comment by KingLyrics** [comment]
> git init `initialize a local git repository`
> git init `initialize a local git repository`

**Comment by KingLyrics** [comment]
1.` git clone > Clone a public repo.`
2.` git status > Check status.`
3.` git add [file-name] > Add a file to staging area`
4.` git commit -m"[commit message]" > Commit changes.`
5.` git rm -r [filename.txt] > Remove a file or folder.`
6. `git branch -a > Create a new branch.`
7. `git branch -d > Delete a branch.`
8. `git push origin --delete[branch name] > Delete a remote branch`
9.  `git checkout [branch name] > switch to branch` 
10. `git push -u origin[branch name] > push to remote repo and remember the branch`
11. `git pull > update local rep to the newest commit`
12. `git log > View changes`
13. `git revert commit [id] > Revert commit changes`
