### ISSUE TITLE
Remove large files from the git history

### ISSUE THREAD

**Issue by gmagnenat** [gmagnenat/equalizer-landing-page#38]

**Comment by gmagnenat** [comment]
Research and find the best way to complete this. 
Large pile of cache files have been added in past commit and make the repository quite heavy.

**Comment by KingLyrics** [comment]
Alright

**Comment by KingLyrics** [comment]
![Screenshot (30)](https://user-images.githubusercontent.com/56762105/182201990-31cff648-2785-4eef-942d-32748bed62e6.png)



I think the yarn files commit might have been where the issue began.
