### ISSUE TITLE
Define git workflow

### ISSUE THREAD

**Issue by gmagnenat** [gmagnenat/equalizer-landing-page#5]

**Comment by gmagnenat** [comment]
### 1
Contributor creates a branch with her/his initials.  
example : "gm-dev"

### 2
The dev branch is pushed to origin
```git push origin gm-dev```

### 3
Create a new pull request to the branch "staging"
Assign a reviewer (another contributor)

### 4
Reviewer merges the pull request into staging

### 5
Code owner merges staging into main

Code reviews and comments are mandatory for merges on the main branch

**Comment by KingLyrics** [comment]
Noted
